from __future__ import annotations

AIRLINES = {
    "AA": "American Airlines",
    "AC": "Air Canada",
    "AF": "Air France",
    "AI": "Air India",
    "AY": "Finnair",
    "AZ": "ITA Airways",
    "BA": "British Airways",
    "CX": "Cathay Pacific",
    "DL": "Delta",
    "EI": "Aer Lingus",
    "EK": "Emirates",
    "ET": "Ethiopian Airlines",
    "EW": "Eurowings",
    "EY": "Etihad",
    "FR": "Ryanair",
    "HA": "Hawaiian Airlines",
    "HV": "Transavia",
    "IB": "Iberia",
    "JL": "Japan Airlines",
    "KE": "Korean Air",
    "KL": "KLM",
    "LH": "Lufthansa",
    "LO": "LOT Polish",
    "LX": "Swiss",
    "NH": "ANA",
    "NK": "Spirit",
    "OR": "TUI fly",
    "OS": "Austrian",
    "OZ": "Asiana",
    "PC": "Pegasus",
    "QF": "Qantas",
    "QR": "Qatar Airways",
    "SK": "SAS",
    "SN": "Brussels Airlines",
    "SQ": "Singapore Airlines",
    "SU": "Aeroflot",
    "TK": "Turkish Airlines",
    "TP": "TAP Portugal",
    "U2": "easyJet",
    "UA": "United",
    "VY": "Vueling",
    "W6": "Wizz Air",
    "WN": "Southwest",
}


def airline_name(code: str) -> str:
    """Return the full airline name for an IATA code, or the code itself if unknown."""
    return AIRLINES.get(code.upper(), code)
