from __future__ import annotations

AIRPORTS = {
    # Major European hubs
    "AMS": "Amsterdam",
    "LHR": "London Heathrow",
    "LGW": "London Gatwick",
    "STN": "London Stansted",
    "LTN": "London Luton",
    "CDG": "Paris CDG",
    "ORY": "Paris Orly",
    "FRA": "Frankfurt",
    "MUC": "Munich",
    "BER": "Berlin",
    "MAD": "Madrid",
    "BCN": "Barcelona",
    "ALC": "Alicante",
    "AGP": "Malaga",
    "PMI": "Palma de Mallorca",
    "FCO": "Rome Fiumicino",
    "MXP": "Milan Malpensa",
    "VCE": "Venice",
    "NAP": "Naples",
    "LIS": "Lisbon",
    "OPO": "Porto",
    "FAO": "Faro",
    "ATH": "Athens",
    "SKG": "Thessaloniki",
    "IST": "Istanbul",
    "SAW": "Istanbul Sabiha",
    "VIE": "Vienna",
    "ZRH": "Zurich",
    "GVA": "Geneva",
    "BRU": "Brussels",
    "CPH": "Copenhagen",
    "OSL": "Oslo",
    "ARN": "Stockholm",
    "HEL": "Helsinki",
    "WAW": "Warsaw",
    "PRG": "Prague",
    "BUD": "Budapest",
    "OTP": "Bucharest",
    "SOF": "Sofia",
    "ZAG": "Zagreb",
    "DUB": "Dublin",
    "EDI": "Edinburgh",
    "KEF": "Reykjavik",
    "TFS": "Tenerife South",
    "LPA": "Gran Canaria",
    "HER": "Heraklion",
    "DUS": "Dusseldorf",
    "HAM": "Hamburg",
    "CGN": "Cologne",
    "EIN": "Eindhoven",
    "RTM": "Rotterdam",
    "CRL": "Brussels Charleroi",
    "LGG": "Liege",
    "NRN": "Weeze (Niederrhein)",
    # North America
    "JFK": "New York JFK",
    "EWR": "Newark",
    "LGA": "New York LaGuardia",
    "LAX": "Los Angeles",
    "SFO": "San Francisco",
    "ORD": "Chicago O'Hare",
    "ATL": "Atlanta",
    "MIA": "Miami",
    "DFW": "Dallas",
    "IAH": "Houston",
    "SEA": "Seattle",
    "BOS": "Boston",
    "DEN": "Denver",
    "IAD": "Washington Dulles",
    "DCA": "Washington Reagan",
    "YYZ": "Toronto",
    "YVR": "Vancouver",
    "YUL": "Montreal",
    "MEX": "Mexico City",
    "CUN": "Cancun",
    # Asia
    "NRT": "Tokyo Narita",
    "HND": "Tokyo Haneda",
    "KIX": "Osaka Kansai",
    "ICN": "Seoul Incheon",
    "PEK": "Beijing",
    "PVG": "Shanghai Pudong",
    "HKG": "Hong Kong",
    "SIN": "Singapore",
    "BKK": "Bangkok",
    "KUL": "Kuala Lumpur",
    "CGK": "Jakarta",
    "DEL": "Delhi",
    "BOM": "Mumbai",
    "TPE": "Taipei",
    "MNL": "Manila",
    "SGN": "Ho Chi Minh City",
    "HAN": "Hanoi",
    # Middle East
    "DXB": "Dubai",
    "AUH": "Abu Dhabi",
    "DOH": "Doha",
    "TLV": "Tel Aviv",
    "AMM": "Amman",
    "CAI": "Cairo",
    "RUH": "Riyadh",
    "JED": "Jeddah",
    # Africa
    "JNB": "Johannesburg",
    "CPT": "Cape Town",
    "NBO": "Nairobi",
    "CMN": "Casablanca",
    "RAK": "Marrakech",
    # South America
    "GRU": "São Paulo",
    "GIG": "Rio de Janeiro",
    "EZE": "Buenos Aires",
    "BOG": "Bogota",
    "SCL": "Santiago",
    "LIM": "Lima",
    # Oceania
    "SYD": "Sydney",
    "MEL": "Melbourne",
    "AKL": "Auckland",
}


def airport_name(iata: str) -> str:
    return AIRPORTS.get(iata.upper(), iata)


def route_name(origin: str, destination: str) -> str:
    return f"{airport_name(origin)} → {airport_name(destination)}"
